- name: Hexo Action
  uses: sma11black/hexo-action@v1.0.1
  with:
    # Github user name
    user_name: saadiha
    # Github email
    user_email: saadiha2016@gmail.com
    # The deploy key for Github Pages repo
    deploy_key: # 123 
    # Git commit messages to your GitHub Pages repository.
    commit_msg: # change
